eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.99.1:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8081
spring:
  application:
    name: flight-booking-ws
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      enabled: false
  datasource:
    password: pass@word1
    url: jdbc:mysql://localhost:3306/flight_booking
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
